/**
 * MASTEROPS RBAC PERMISSION MATRICES
 * Defines the complete permission structure based on RBAC Sovereign Document v1.0
 */

import {
  UserRole,
  WorkspaceRole,
  ExternalRole,
  ProductionPhase,
  AssetType,
  AssetAction,
  ProjectAction,
  ArchiveAction,
  WorkspaceAction,
  AccessLevel,
  PhaseAccessMatrix,
} from './types';

// ============================================
// ROLE HIERARCHY (Escalation Priority)
// ============================================

export const ROLE_HIERARCHY: Record<UserRole, number> = {
  // Internal roles (higher = more authority)
  WORKSPACE_OWNER: 100,
  WORKSPACE_ADMIN: 90,
  LEGAL: 85,             // Legal has special override authority
  EXECUTIVE: 70,
  PRODUCER: 60,
  FINANCE: 55,
  EDITOR: 40,
  MARKETING: 35,

  // External roles (always lower)
  EXTERNAL_EDITOR: 20,
  EXTERNAL_VENDOR: 15,
  EXTERNAL_REVIEWER: 10,
  GUEST_VIEWER: 5,
};

// ============================================
// INTERNAL VS EXTERNAL ROLE CLASSIFICATION
// ============================================

export const INTERNAL_ROLES: WorkspaceRole[] = [
  'WORKSPACE_OWNER',
  'WORKSPACE_ADMIN',
  'EXECUTIVE',
  'PRODUCER',
  'EDITOR',
  'MARKETING',
  'LEGAL',
  'FINANCE',
];

export const EXTERNAL_ROLES: ExternalRole[] = [
  'EXTERNAL_EDITOR',
  'EXTERNAL_REVIEWER',
  'EXTERNAL_VENDOR',
  'GUEST_VIEWER',
];

// ============================================
// PHASE-BASED ACCESS MATRIX
// ============================================

export const PHASE_ACCESS_MATRIX: PhaseAccessMatrix[] = [
  {
    phase: 'BRIEF',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'LEGAL', 'FINANCE'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE'],
    externalAllowed: false,
  },
  {
    phase: 'PRE_PRODUCTION',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'LEGAL', 'FINANCE'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'FINANCE', 'LEGAL'],
    externalAllowed: false,
  },
  {
    phase: 'PRODUCTION',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'EDITOR', 'LEGAL'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER', 'EDITOR'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    externalAllowed: true, // External Editors if assigned
  },
  {
    phase: 'POST_PRODUCTION',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'EDITOR', 'LEGAL'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER', 'EDITOR'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    externalAllowed: true, // External Editors for specific tasks
  },
  {
    phase: 'INTERNAL_REVIEW',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'EDITOR', 'MARKETING', 'LEGAL', 'FINANCE'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE'],
    externalAllowed: false,
  },
  {
    phase: 'EXTERNAL_REVIEW',
    owner: 'PRODUCER',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'MARKETING', 'LEGAL'],
    canEdit: [],
    canApprove: [],
    externalAllowed: true, // External Reviewers (version-scoped)
  },
  {
    phase: 'LEGAL_APPROVAL',
    owner: 'LEGAL',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'LEGAL'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'LEGAL'],
    canApprove: ['WORKSPACE_OWNER', 'LEGAL'],
    externalAllowed: false,
  },
  {
    phase: 'DISTRIBUTION',
    owner: 'MARKETING',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'EXECUTIVE', 'PRODUCER', 'MARKETING', 'LEGAL'],
    canEdit: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'MARKETING'],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'PRODUCER'],
    externalAllowed: false,
  },
  {
    phase: 'ARCHIVE',
    owner: 'WORKSPACE_ADMIN',
    canView: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'LEGAL'],
    canEdit: [],
    canApprove: ['WORKSPACE_OWNER', 'WORKSPACE_ADMIN', 'LEGAL'],
    externalAllowed: false, // Never for externals
  },
];

// ============================================
// ASSET-TYPE ACCESS MATRIX
// ============================================

type AssetAccessMap = Record<AssetType, Record<UserRole, AccessLevel>>;

export const ASSET_TYPE_ACCESS: AssetAccessMap = {
  RAW_FOOTAGE: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'NONE',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'NONE',
  },
  AUDIO: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'NONE',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: 'NONE',
  },
  ROUGH_CUT: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'NONE',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'APPROVED_ONLY',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'NONE',
  },
  MASTER: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'VIEW_ONLY',
    LEGAL: 'FULL', // Can approve
    FINANCE: 'VIEW_ONLY',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'APPROVED_ONLY',
    EXTERNAL_VENDOR: 'APPROVED_ONLY',
    GUEST_VIEWER: 'NONE',
  },
  LEGAL_DOCUMENT: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'VIEW_ONLY',
    EDITOR: 'NONE',
    MARKETING: 'NONE',
    LEGAL: 'FULL',
    FINANCE: 'SCOPED', // Conditional
    EXTERNAL_EDITOR: 'NONE',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'NONE',
  },
  VERSION: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'APPROVED_ONLY',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'SCOPED',
  },
  LOCALIZED_VERSION: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'VIEW_ONLY',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED', // Client market only
    EXTERNAL_VENDOR: 'SCOPED', // Upload only
    GUEST_VIEWER: 'NONE',
  },
  ARCHIVE_ASSET: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'SCOPED',
    EDITOR: 'NONE',
    MARKETING: 'NONE',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'VIEW_ONLY', // Cost view
    EXTERNAL_EDITOR: 'NONE',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'NONE',
  },
  PROJECT_FILE: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'NONE',
    LEGAL: 'NONE',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'NONE',
    GUEST_VIEWER: 'NONE',
  },
  GRAPHICS: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'VIEW_ONLY',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'APPROVED_ONLY',
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: 'NONE',
  },
  MUSIC: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'VIEW_ONLY',
    LEGAL: 'FULL', // Must approve
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'NONE',
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: 'NONE',
  },
  VFX: {
    WORKSPACE_OWNER: 'FULL',
    WORKSPACE_ADMIN: 'FULL',
    EXECUTIVE: 'VIEW_ONLY',
    PRODUCER: 'FULL',
    EDITOR: 'FULL',
    MARKETING: 'NONE',
    LEGAL: 'VIEW_ONLY',
    FINANCE: 'NONE',
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'APPROVED_ONLY',
    EXTERNAL_VENDOR: 'SCOPED', // VFX vendors
    GUEST_VIEWER: 'NONE',
  },
};

// ============================================
// ACTION-LEVEL PERMISSION MATRIX
// ============================================

type ActionPermissionMap = Record<AssetAction, Record<UserRole, boolean | 'SCOPED'>>;

export const ASSET_ACTION_PERMISSIONS: ActionPermissionMap = {
  VIEW: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: 'SCOPED', // Approved only
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED',
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: 'SCOPED',
  },
  EDIT: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: 'SCOPED', // Assigned only
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: 'SCOPED', // Upload only
    GUEST_VIEWER: false,
  },
  UPLOAD: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: false,
  },
  DELETE: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  DOWNLOAD_PROXY: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: false,
  },
  DOWNLOAD_MASTER: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: 'SCOPED', // Restricted
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: false,
  },
  APPROVE: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true, // Final legal approval
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  REQUEST_REVIEW: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: true,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  ADD_COMMENT: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: true,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED',
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  ADD_ANNOTATION: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: true,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED',
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
};

// ============================================
// PROJECT ACTION PERMISSIONS
// ============================================

type ProjectActionPermissionMap = Record<ProjectAction, Record<UserRole, boolean | 'SCOPED'>>;

export const PROJECT_ACTION_PERMISSIONS: ProjectActionPermissionMap = {
  VIEW_PROJECT: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: true,
    MARKETING: true,
    LEGAL: true,
    FINANCE: true,
    EXTERNAL_EDITOR: 'SCOPED',
    EXTERNAL_REVIEWER: 'SCOPED',
    EXTERNAL_VENDOR: 'SCOPED',
    GUEST_VIEWER: 'SCOPED',
  },
  EDIT_PROJECT: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  DELETE_PROJECT: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_TEAM: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_BUDGET: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_BUDGET: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  APPROVE_BUDGET: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_LEGAL_PANEL: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_LEGAL: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  SHARE_EXTERNAL: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  CREATE_REVIEW_LINK: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  ADVANCE_PHASE: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: 'SCOPED', // Only legal phases
    FINANCE: 'SCOPED', // Only budget phases
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
};

// ============================================
// ARCHIVE ACTION PERMISSIONS
// ============================================

type ArchiveActionPermissionMap = Record<ArchiveAction, Record<UserRole, boolean | 'SCOPED'>>;

export const ARCHIVE_ACTION_PERMISSIONS: ArchiveActionPermissionMap = {
  VIEW_ARCHIVE_LISTING: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_ARCHIVE_ASSET: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_METADATA: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  DOWNLOAD_ARCHIVE_PROXY: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  DOWNLOAD_ARCHIVE_MASTER: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  RESTORE_ASSET: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  REQUEST_THAW: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  APPROVE_THAW: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: true, // Finance can approve/block based on cost
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  DELETE_ARCHIVED: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  SEARCH_ARCHIVE: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_KNOWLEDGE_GRAPH: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: 'SCOPED',
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
};

// ============================================
// WORKSPACE ACTION PERMISSIONS
// ============================================

type WorkspaceActionPermissionMap = Record<WorkspaceAction, Record<UserRole, boolean>>;

export const WORKSPACE_ACTION_PERMISSIONS: WorkspaceActionPermissionMap = {
  MANAGE_WORKSPACE: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_BILLING: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: false,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_USERS: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_AUDIT_LOGS: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  EXPORT_AUDIT_LOGS: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: true,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_INTEGRATIONS: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  MANAGE_SSO: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: false,
    PRODUCER: false,
    EDITOR: false,
    MARKETING: false,
    LEGAL: false,
    FINANCE: false,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
  VIEW_ANALYTICS: {
    WORKSPACE_OWNER: true,
    WORKSPACE_ADMIN: true,
    EXECUTIVE: true,
    PRODUCER: true,
    EDITOR: false,
    MARKETING: true,
    LEGAL: false,
    FINANCE: true,
    EXTERNAL_EDITOR: false,
    EXTERNAL_REVIEWER: false,
    EXTERNAL_VENDOR: false,
    GUEST_VIEWER: false,
  },
};

// ============================================
// ROLE DISPLAY NAMES
// ============================================

export const ROLE_DISPLAY_NAMES: Record<UserRole, string> = {
  WORKSPACE_OWNER: 'Workspace Owner',
  WORKSPACE_ADMIN: 'Workspace Admin',
  EXECUTIVE: 'Executive / Stakeholder',
  PRODUCER: 'Producer',
  EDITOR: 'Editor / Creative',
  MARKETING: 'Marketing / Comms',
  LEGAL: 'Legal',
  FINANCE: 'Finance',
  EXTERNAL_EDITOR: 'External Editor',
  EXTERNAL_REVIEWER: 'External Reviewer',
  EXTERNAL_VENDOR: 'External Vendor',
  GUEST_VIEWER: 'Guest Viewer',
};

// ============================================
// ROLE DESCRIPTIONS
// ============================================

export const ROLE_DESCRIPTIONS: Record<UserRole, string> = {
  WORKSPACE_OWNER: 'Root admin with full control over workspace, billing, and global rules',
  WORKSPACE_ADMIN: 'Manages roles, policies, and cross-project access',
  EXECUTIVE: 'Oversight, approval, and dashboard access',
  PRODUCER: 'Manages all project phases, permissions, and progress',
  EDITOR: 'Works on assigned assets, uploads, and submits versions',
  MARKETING: 'Views approved cuts, requests versions, and publishes',
  LEGAL: 'Rights approvals, locks assets, and restricts access',
  FINANCE: 'Budget approvals, tracks costs, controls expensive operations',
  EXTERNAL_EDITOR: 'Can access only assigned tasks/assets; no archive or workspace visibility',
  EXTERNAL_REVIEWER: 'View-only access to assigned versions; cannot browse project',
  EXTERNAL_VENDOR: 'Upload to controlled folders; download approved assets only',
  GUEST_VIEWER: 'Time-limited, watermark-only viewing; no download',
};
